namespace TheBlazorState.Abstractions;

/// <summary>
/// Implemented by shared state classes to notify consuming components of changes.
/// Generated by the source generator for classes with [Shared] properties.
/// </summary>
public interface INotifyStateChanged
{
    /// <summary>Fires when any [Shared] property on this state class changes.</summary>
    event Action? StateChanged;
}
