using System;
using System.Collections.Generic;
using System.Text;

namespace BlazorStatePlus.Generators;

internal static class Emitter
{
    public static string Emit(ComponentModel model)
    {
        if (model == null) throw new ArgumentNullException("model");

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.AspNetCore.Components;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }
        if (model.UserImplementsDisposable)
            sb.AppendLine($"partial class {model.ClassName}");
        else
            sb.AppendLine($"partial class {model.ClassName} : global::System.IDisposable");

        sb.AppendLine("{");

        // --- Injected StateManager field (hidden from editor) ---
        sb.AppendLine("    [global::Microsoft.AspNetCore.Components.Inject]");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    private global::BlazorStatePlus.Services.StateManager __sm { get; set; } = null!;");
        sb.AppendLine();

        // --- SliceInitContext? __ctx field ---
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"    private {model.ClassName}.SliceInitContext? __ctx;");
        sb.AppendLine();

        // --- OnInitialized override ---
        sb.AppendLine("    protected override void OnInitialized()");
        sb.AppendLine("    {");
        sb.AppendLine("        base.OnInitialized();");
        sb.AppendLine();
        sb.AppendLine($"        var __ctxLocal = new {model.ClassName}.SliceInitContext();");
        sb.AppendLine("        OnInitializeSlices(__ctxLocal);");
        sb.AppendLine();

        foreach (var field in model.Fields)
        {
            var optionsArg = BuildOptionsArg(field);
            sb.AppendLine($"        {field.FieldName} = __sm.CreateSlice<{field.FullTypeArgument}>(");
            sb.AppendLine($"            __ctxLocal.{field.PropertyName}.ResolveKey(\"{EscapeString(field.BaseKey)}\"),");
            sb.AppendLine($"            __ctxLocal.{field.PropertyName}.GetDefaultValue(),");
            sb.AppendLine($"            {optionsArg});");
        }

        sb.AppendLine();
        sb.AppendLine("        __ctx = __ctxLocal.HasAsyncInit ? __ctxLocal : null;");

        if (model.UserOverridesOnInitialized)
        {
            sb.AppendLine("        OnAfterSlicesCreated();");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // --- OnInitializedAsync override ---
        sb.AppendLine("    protected override async global::System.Threading.Tasks.Task OnInitializedAsync()");
        sb.AppendLine("    {");
        sb.AppendLine("        await base.OnInitializedAsync();");
        sb.AppendLine();
        sb.AppendLine("        if (__ctx is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var __ctxLocal = __ctx;");
        sb.AppendLine("            __ctx = null;");
        sb.AppendLine();

        foreach (var field in model.Fields)
        {
            sb.AppendLine($"            await __ctxLocal.{field.PropertyName}.InitializeAsync({field.FieldName});");
        }

        sb.AppendLine("        }");

        if (model.UserOverridesOnInitializedAsync)
        {
            sb.AppendLine();
            sb.AppendLine("        await OnAfterSlicesInitializedAsync();");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // --- partial void OnInitializeSlices ---
        sb.AppendLine($"    partial void OnInitializeSlices({model.ClassName}.SliceInitContext ctx);");
        sb.AppendLine();

        // --- partial void OnAfterSlicesCreated (only if user overrides OnInitialized) ---
        if (model.UserOverridesOnInitialized)
        {
            sb.AppendLine("    partial void OnAfterSlicesCreated();");
            sb.AppendLine();
        }

        // --- partial Task OnAfterSlicesInitializedAsync (only if user overrides OnInitializedAsync) ---
        if (model.UserOverridesOnInitializedAsync)
        {
            sb.AppendLine("    partial global::System.Threading.Tasks.Task OnAfterSlicesInitializedAsync();");
            sb.AppendLine();
        }

        // --- Dispose ---
        if (model.UserImplementsDisposable)
        {
            // User handles IDisposable; emit a private helper they must call
            sb.AppendLine("    private void __DisposeSlices()");
            sb.AppendLine("    {");
            foreach (var field in model.Fields)
            {
                sb.AppendLine($"        {field.FieldName}?.Dispose();");
            }
            // StateManager is DI-scoped; don't dispose it here
            sb.AppendLine("    }");
        }
        else
        {
            // Generator owns IDisposable
            sb.AppendLine("    public void Dispose()");
            sb.AppendLine("    {");
            foreach (var field in model.Fields)
            {
                sb.AppendLine($"        {field.FieldName}?.Dispose();");
            }
            // StateManager is DI-scoped; don't dispose it here
            sb.AppendLine("    }");
        }

        sb.AppendLine();

        // --- Nested SliceInitContext class ---
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    public sealed class SliceInitContext");
        sb.AppendLine("    {");

        foreach (var field in model.Fields)
        {
            sb.AppendLine($"        public global::BlazorStatePlus.Generators.SliceBuilder<{field.FullTypeArgument}> {field.PropertyName} {{ get; }} = new global::BlazorStatePlus.Generators.SliceBuilder<{field.FullTypeArgument}>();");
        }

        sb.AppendLine();
        sb.AppendLine("        public bool HasAsyncInit");
        sb.AppendLine("        {");
        sb.AppendLine("            get");
        sb.AppendLine("            {");

        if (model.Fields.Count == 0)
        {
            sb.AppendLine("                return false;");
        }
        else
        {
            sb.Append("                return ");
            for (int i = 0; i < model.Fields.Count; i++)
            {
                if (i > 0) sb.Append(" || ");
                sb.Append($"{model.Fields[i].PropertyName}.HasAsyncFactory");
            }
            sb.AppendLine(";");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Builds the options argument (3rd param to CreateSlice).
    /// If neither TimeToLive nor AllowUpdatesOnNavigation is set on the attribute,
    /// we delegate fully to the builder (which may return null).
    /// If either is set, we bake the attribute defaults as a lambda and merge with
    /// the builder's user-supplied overrides.
    /// </summary>
    private static string BuildOptionsArg(SliceFieldModel field)
    {
        bool hasTtl = !string.IsNullOrEmpty(field.TimeToLive);
        bool hasAllow = field.AllowUpdatesOnNavigation;

        if (!hasTtl && !hasAllow)
        {
            // No attribute-level defaults — let the builder decide (may be null)
            return $"__ctxLocal.{field.PropertyName}.BuildOptions()";
        }

        // Build an attribute-defaults lambda
        var lambdaParts = new List<string>();

        if (hasTtl)
        {
            lambdaParts.Add($"__o.TimeToLive = global::System.TimeSpan.Parse(\"{EscapeString(field.TimeToLive!)}\")");
        }

        if (hasAllow)
        {
            lambdaParts.Add("__o.AllowUpdatesOnNavigation = true");
        }

        var lambda = $"__o => {{ {string.Join("; ", lambdaParts)}; }}";
        return $"__ctxLocal.{field.PropertyName}.BuildOptions({lambda})";
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
