//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectCalisthenics {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ObjectCalisthenics.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AB0001Description {
            get {
                return ResourceManager.GetString("AB0001Description", resourceCulture);
            }
        }
        
        internal static string AB0001MessageFormat {
            get {
                return ResourceManager.GetString("AB0001MessageFormat", resourceCulture);
            }
        }
        
        internal static string AB0001Title {
            get {
                return ResourceManager.GetString("AB0001Title", resourceCulture);
            }
        }
        
        internal static string AB0001CodeFixTitle {
            get {
                return ResourceManager.GetString("AB0001CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AB0002Description {
            get {
                return ResourceManager.GetString("AB0002Description", resourceCulture);
            }
        }
        
        internal static string AB0002MessageFormat {
            get {
                return ResourceManager.GetString("AB0002MessageFormat", resourceCulture);
            }
        }
        
        internal static string AB0002Title {
            get {
                return ResourceManager.GetString("AB0002Title", resourceCulture);
            }
        }
        
        internal static string OC0001Title {
            get {
                return ResourceManager.GetString("OC0001Title", resourceCulture);
            }
        }
        
        internal static string OC0001Description {
            get {
                return ResourceManager.GetString("OC0001Description", resourceCulture);
            }
        }
        
        internal static string OC0001MessageFormat {
            get {
                return ResourceManager.GetString("OC0001MessageFormat", resourceCulture);
            }
        }
        
        internal static string OC0002Title {
            get {
                return ResourceManager.GetString("OC0002Title", resourceCulture);
            }
        }
        
        internal static string OC0002Description {
            get {
                return ResourceManager.GetString("OC0002Description", resourceCulture);
            }
        }
        
        internal static string OC0002MessageFormat {
            get {
                return ResourceManager.GetString("OC0002MessageFormat", resourceCulture);
            }
        }
        
        internal static string OC0003Title {
            get {
                return ResourceManager.GetString("OC0003Title", resourceCulture);
            }
        }
        
        internal static string OC0003Description {
            get {
                return ResourceManager.GetString("OC0003Description", resourceCulture);
            }
        }
        
        internal static string OC0003MessageFormat {
            get {
                return ResourceManager.GetString("OC0003MessageFormat", resourceCulture);
            }
        }
        
        internal static string OC0004Title {
            get {
                return ResourceManager.GetString("OC0004Title", resourceCulture);
            }
        }
        
        internal static string OC0004Description {
            get {
                return ResourceManager.GetString("OC0004Description", resourceCulture);
            }
        }
        
        internal static string OC0004MessageFormat {
            get {
                return ResourceManager.GetString("OC0004MessageFormat", resourceCulture);
            }
        }
        
        internal static string OC0005Title {
            get {
                return ResourceManager.GetString("OC0005Title", resourceCulture);
            }
        }
        
        internal static string OC0005Description {
            get {
                return ResourceManager.GetString("OC0005Description", resourceCulture);
            }
        }
        
        internal static string OC0005MessageFormat {
            get {
                return ResourceManager.GetString("OC0005MessageFormat", resourceCulture);
            }
        }
        
        internal static string OC0006Title {
            get {
                return ResourceManager.GetString("OC0006Title", resourceCulture);
            }
        }
        
        internal static string OC0006Description {
            get {
                return ResourceManager.GetString("OC0006Description", resourceCulture);
            }
        }
        
        internal static string OC0006MessageFormat {
            get {
                return ResourceManager.GetString("OC0006MessageFormat", resourceCulture);
            }
        }
        
        internal static string OC0007Title {
            get {
                return ResourceManager.GetString("OC0007Title", resourceCulture);
            }
        }
        
        internal static string OC0007Description {
            get {
                return ResourceManager.GetString("OC0007Description", resourceCulture);
            }
        }
        
        internal static string OC0007MessageFormat {
            get {
                return ResourceManager.GetString("OC0007MessageFormat", resourceCulture);
            }
        }
        
        internal static string OC0008Title {
            get {
                return ResourceManager.GetString("OC0008Title", resourceCulture);
            }
        }
        
        internal static string OC0008Description {
            get {
                return ResourceManager.GetString("OC0008Description", resourceCulture);
            }
        }
        
        internal static string OC0008MessageFormat {
            get {
                return ResourceManager.GetString("OC0008MessageFormat", resourceCulture);
            }
        }
        
        internal static string OC0009Title {
            get {
                return ResourceManager.GetString("OC0009Title", resourceCulture);
            }
        }
        
        internal static string OC0009Description {
            get {
                return ResourceManager.GetString("OC0009Description", resourceCulture);
            }
        }
        
        internal static string OC0009MessageFormat {
            get {
                return ResourceManager.GetString("OC0009MessageFormat", resourceCulture);
            }
        }
    }
}
