using System.Text;

namespace TheBlazorState.Generators;

internal static class InjectSubscriptionEmitter
{
    public static string Emit(InjectSubscriptionModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        // For components WITH [Persist]: emit partial methods that PersistEmitter calls
        // For components WITHOUT [Persist]: emit full OnInitialized + Dispose
        if (model.HasPersistProperties)
        {
            sb.AppendLine($"partial class {model.ClassName}");
            sb.AppendLine("{");

            // Partial methods called by PersistEmitter
            sb.AppendLine("    partial void __SubscribeToSharedState()");
            sb.AppendLine("    {");
            foreach (var name in model.SharedStatePropertyNames)
            {
                sb.AppendLine($"        {name}.StateChanged += __OnSharedStateChanged;");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    partial void __UnsubscribeFromSharedState()");
            sb.AppendLine("    {");
            foreach (var name in model.SharedStatePropertyNames)
            {
                sb.AppendLine($"        {name}.StateChanged -= __OnSharedStateChanged;");
            }
            sb.AppendLine("    }");
        }
        else
        {
            // Full lifecycle — no PersistGenerator involved
            if (model.UserImplementsDisposable)
                sb.AppendLine($"partial class {model.ClassName}");
            else
                sb.AppendLine($"partial class {model.ClassName} : global::System.IDisposable");

            sb.AppendLine("{");

            sb.AppendLine("    protected override void OnInitialized()");
            sb.AppendLine("    {");
            sb.AppendLine("        base.OnInitialized();");
            foreach (var name in model.SharedStatePropertyNames)
            {
                sb.AppendLine($"        {name}.StateChanged += __OnSharedStateChanged;");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private void __OnSharedStateChanged() => InvokeAsync(StateHasChanged);");
            sb.AppendLine();

            sb.AppendLine("    public void Dispose()");
            sb.AppendLine("    {");
            foreach (var name in model.SharedStatePropertyNames)
            {
                sb.AppendLine($"        {name}.StateChanged -= __OnSharedStateChanged;");
            }
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
