using System;
using System.Text;

namespace TheBlazorState.Generators;

internal static class SharedEmitter
{
    public static string Emit(SharedStateModel model)
    {
        if (model == null) throw new ArgumentNullException("model");

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {model.ClassName} : global::TheBlazorState.Abstractions.INotifyStateChanged");
        sb.AppendLine("{");

        // --- Per-property: backing field, meta, partial property impl, Meta accessor ---
        foreach (var prop in model.Properties)
        {
            string backingField = $"__{prop.PropertyName}_backing";
            string metaField = $"__{prop.PropertyName}_meta";

            sb.AppendLine($"    // --- {prop.PropertyName} ---");

            // Backing field
            sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine($"    private {prop.FullTypeName} {backingField} = default!;");
            sb.AppendLine();

            // Meta field (initialized inline — no lifecycle)
            sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine($"    private global::TheBlazorState.Abstractions.StateMeta {metaField} = new(null);");
            sb.AppendLine();

            // Partial property implementation
            sb.AppendLine($"    public partial {prop.FullTypeName} {prop.PropertyName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        get => {backingField};");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (global::System.Collections.Generic.EqualityComparer<{prop.FullTypeName}>.Default.Equals({backingField}, value))");
            sb.AppendLine("                return;");
            sb.AppendLine($"            {backingField} = value;");
            sb.AppendLine($"            {metaField}.MarkDirty();");
            sb.AppendLine($"            {metaField}.RaiseChanged();");
            sb.AppendLine("            StateChanged?.Invoke();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Public Meta accessor
            sb.AppendLine($"    public global::TheBlazorState.Abstractions.StateMeta {prop.PropertyName}Meta => {metaField};");
            sb.AppendLine();
        }

        // --- StateChanged event ---
        sb.AppendLine("    public event global::System.Action? StateChanged;");

        sb.AppendLine("}");

        return sb.ToString();
    }
}
