using System;
using System.Text;

namespace TheBlazorState.Generators;

internal static class PersistEmitter
{
    public static string Emit(PersistComponentModel model)
    {
        if (model == null) throw new ArgumentNullException("model");

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.AspNetCore.Components;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        if (model.UserImplementsDisposable)
            sb.AppendLine($"partial class {model.ClassName}");
        else
            sb.AppendLine($"partial class {model.ClassName} : global::System.IDisposable");

        sb.AppendLine("{");

        // --- Injected StateManager property ---
        sb.AppendLine("    [global::Microsoft.AspNetCore.Components.Inject]");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    private global::TheBlazorState.Services.StateManager __stateManager { get; set; } = null!;");
        sb.AppendLine();

        // --- Per-property: backing field, meta, partial property impl, Meta accessor ---
        foreach (var prop in model.Properties)
        {
            string backingField = $"__{prop.PropertyName}_backing";
            string metaField = $"__{prop.PropertyName}_meta";

            sb.AppendLine($"    // --- {prop.PropertyName} ---");

            // Backing field
            sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine($"    private {prop.FullTypeName} {backingField} = default!;");
            sb.AppendLine();

            // Meta field
            sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine($"    private global::TheBlazorState.Abstractions.StateMeta {metaField} = null!;");
            sb.AppendLine();

            // Partial property implementation
            sb.AppendLine($"    public partial {prop.FullTypeName} {prop.PropertyName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        get => {backingField};");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (global::System.Collections.Generic.EqualityComparer<{prop.FullTypeName}>.Default.Equals({backingField}, value))");
            sb.AppendLine("                return;");
            sb.AppendLine($"            {backingField} = value;");
            sb.AppendLine($"            if ({metaField} is not null)");
            sb.AppendLine("            {");
            sb.AppendLine($"                {metaField}.MarkDirty();");
            sb.AppendLine($"                {metaField}.RaiseChanged();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Public Meta accessor
            sb.AppendLine($"    public global::TheBlazorState.Abstractions.StateMeta {prop.PropertyName}Meta => {metaField};");
            sb.AppendLine();
        }

        // --- Nested __StateContext ---
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"    public sealed class __StateContext : global::TheBlazorState.Configuration.StateContext");
        sb.AppendLine("    {");

        foreach (var prop in model.Properties)
        {
            sb.AppendLine($"        public global::TheBlazorState.Configuration.PropertyConfigurator<{prop.FullTypeName}> {prop.PropertyName} {{ get; }} = new();");
        }

        sb.AppendLine();
        sb.AppendLine("        public bool HasAsyncInit");
        sb.AppendLine("        {");
        sb.AppendLine("            get");
        sb.AppendLine("            {");

        if (model.Properties.Count == 0)
        {
            sb.AppendLine("                return false;");
        }
        else
        {
            sb.Append("                return ");
            for (int i = 0; i < model.Properties.Count; i++)
            {
                if (i > 0) sb.Append(" || ");
                sb.Append($"{model.Properties[i].PropertyName}.HasAsyncFactory");
            }
            sb.AppendLine(";");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- __stateCtx field ---
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"    private {model.ClassName}.__StateContext? __stateCtx;");
        sb.AppendLine();

        // --- OnInitialized ---
        sb.AppendLine("    protected override void OnInitialized()");
        sb.AppendLine("    {");
        sb.AppendLine("        base.OnInitialized();");
        sb.AppendLine();
        sb.AppendLine($"        var __ctx = new {model.ClassName}.__StateContext();");
        sb.AppendLine("        ConfigureState(__ctx);");
        sb.AppendLine();

        foreach (var prop in model.Properties)
        {
            string backingField = $"__{prop.PropertyName}_backing";
            string metaField = $"__{prop.PropertyName}_meta";
            string ttlArg = prop.TimeToLive != null
                ? $"global::System.TimeSpan.Parse(\"{EscapeString(prop.TimeToLive)}\")"
                : "null";

            sb.AppendLine($"        {metaField} = new global::TheBlazorState.Abstractions.StateMeta({ttlArg});");
            sb.AppendLine($"        if (__ctx.{prop.PropertyName}.HasDefaultValue)");
            sb.AppendLine($"            {backingField} = __ctx.{prop.PropertyName}.GetDefaultValue();");
            sb.AppendLine($"        __stateManager.RestoreProperty<{prop.FullTypeName}>(");
            sb.AppendLine($"            __ctx.{prop.PropertyName}.ResolveKey(\"{EscapeString(prop.BaseKey)}\"),");
            sb.AppendLine($"            {metaField},");
            sb.AppendLine($"            __v => {backingField} = __v,");
            sb.AppendLine($"            () => {backingField});");
            sb.AppendLine($"        {metaField}.OnChanged += () => InvokeAsync(StateHasChanged);");
            sb.AppendLine();
        }

        sb.AppendLine("        __stateCtx = __ctx.HasAsyncInit ? __ctx : null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- OnInitializedAsync ---
        sb.AppendLine("    protected override async global::System.Threading.Tasks.Task OnInitializedAsync()");
        sb.AppendLine("    {");
        sb.AppendLine("        await base.OnInitializedAsync();");
        sb.AppendLine();
        sb.AppendLine("        if (__stateCtx is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var __ctx = __stateCtx;");
        sb.AppendLine("            __stateCtx = null;");
        sb.AppendLine();

        foreach (var prop in model.Properties)
        {
            string backingField = $"__{prop.PropertyName}_backing";
            string metaField = $"__{prop.PropertyName}_meta";

            sb.AppendLine($"            if (__ctx.{prop.PropertyName}.HasAsyncFactory");
            sb.AppendLine($"                && (!{metaField}.WasRestored || {metaField}.IsStale))");
            sb.AppendLine("            {");
            sb.AppendLine($"                {backingField} = await __ctx.{prop.PropertyName}.InvokeFactoryAsync();");
            sb.AppendLine($"                {metaField}.MarkDirty();");
            sb.AppendLine("            }");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // --- partial void ConfigureState ---
        sb.AppendLine($"    partial void ConfigureState({model.ClassName}.__StateContext ctx);");
        sb.AppendLine();

        // --- Dispose ---
        sb.AppendLine("    public void Dispose()");
        sb.AppendLine("    {");
        foreach (var prop in model.Properties)
        {
            sb.AppendLine($"        __{prop.PropertyName}_meta?.ClearHandlers();");
        }
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
